### ISSUE TITLE
[BUG] Run onnx-simplifier by onnxruntime-gpu

### ISSUE THREAD

**Issue by chiehpower** [daquexian/onnx-simplifier#52]
Hi all, 
I can run the onnx-simplifier by onnxruntime cpu version without any issue. 
However, when I run by onnxruntime gpu version, it got stuck.

Command:
```
python3 -m onnxsim ./model.onnx ./model_simplifier.onnx  
```
Output:
```
Simplifying...
2020-03-26 10:49:43.826186091 [E:onnxruntime:, sequential_executor.cc:183 Execute] Non-zero status code returned while running Add node. Name:'' Status Message: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:97 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:91 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 2: out of memory ; GPU=0 ; hostname=chieh-Z97X-UD3H ; expr=cudaMalloc((void**)&p, size); 
Stacktrace:

Stacktrace:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/__main__.py", line 42, in <module>
  File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/__main__.py", line 31, in main
  File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/onnx_simplifier.py", line 303, in simplify
  File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/onnx_simplifier.py", line 158, in forward_all
  File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/onnx_simplifier.py", line 149, in forward
  File "/home/chieh/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 142, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'' Status Message: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:97 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:91 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 2: out of memory ; GPU=0 ; hostname=chieh-Z97X-UD3H ; expr=cudaMalloc((void**)&p, size); 
Stacktrace:

Stacktrace:
```
I try to install both versions (cpu and gpu) in the same time, but my onnxruntime-gpu cannot be used after I install the cpu version. 
I need to use onnxruntime by gpu, so I have to uninstall cpu version. 
Is there any method to assign running cpu by onnxruntime-gpu? Or how can I solve this issue?

Thank you.  

**System information**
- OS Platform and Distribution : Linux Ubuntu 18.04)
- ONNX Runtime installed from (source or binary): install by pip
- ONNX Runtime GPU version: 1.1.2
- Python version: 3.6.9
- CUDA/cuDNN version: 10.0 / 7.6.5
- GPU model and memory: GTX 1060 / 6G

**Comment by briliantnugraha** [comment]
It is solved after downgrading with onnxruntime-gpu==1.1.2
The issue is that onnxruntime-gpu 1.2.0 will use CUDA 10.1 by [default](https://github.com/Microsoft/onnxruntime/releases/tag/v1.2.0).

To use it with older CUDA version (or 10.2), please use v1.1.2 instead~

**Comment by chiehpower** [comment]
> It is solved after downgrading with onnxruntime-gpu==1.1.2
> The issue is that onnxruntime-gpu 1.2.0 will use CUDA 10.1 by [default](https://github.com/Microsoft/onnxruntime/releases/tag/v1.2.0).
> 
> To use it with older CUDA version (or 10.2), please use v1.1.2 instead~

Mine is also installed by Onnxruntime gpu 1.1.2 version. 
when I run the command, the gpu will overtake 6GB...

**Comment by daquexian** [comment]
Thanks for your report. CPU will be always used since v0.2.7. Please upgrade onnxsim.

**Comment by chiehpower** [comment]
> Thanks for your report. CPU will be always used since v0.2.7. Please upgrade onnxsim and have a try.

@daquexian  Thanks for your reply!! 
After I git pull the latest version, I uninstall onnxruntime and onnxruntime-gpu again, and then I directly install onnxruntime-gpu 1.1.2 version again.
My command is as same as previous one.
```
python3 -m onnxsim model.onnx model_simplifier.onnx  
```

However, I still get this result below.
```
Simplifying...
2020-03-30 08:49:02.853713051 [E:onnxruntime:, sequential_executor.cc:183 Execute] Non-zero status code returned while running Add node. Name:'' Status Message: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:97 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:91 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 2: out of memory ; GPU=0 ; hostname=chieh-Z97X-UD3H ; expr=cudaMalloc((void**)&p, size); 
Stacktrace:

Stacktrace:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/__main__.py", line 42, in <module>
  File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/__main__.py", line 31, in main
  File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/onnx_simplifier.py", line 303, in simplify
  File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/onnx_simplifier.py", line 158, in forward_all
  File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/onnx_simplifier.py", line 149, in forward
  File "/home/chieh/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 142, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'' Status Message: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:97 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:91 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 2: out of memory ; GPU=0 ; hostname=chieh-Z97X-UD3H ; expr=cudaMalloc((void**)&p, size); 
Stacktrace:

Stacktrace:
```
Do you know how to fix this error?

Thank you.

**Comment by daquexian** [comment]
> > Thanks for your report. CPU will be always used since v0.2.7. Please upgrade onnxsim and have a try.
> 
> @daquexian  Thanks for your reply!! 
> After I git pull the latest version, I uninstall onnxruntime and onnxruntime-gpu again, and then I directly install onnxruntime-gpu 1.1.2 version again.
> My command is as same as previous one.
> ```
> python3 -m onnxsim model.onnx model_simplifier.onnx  
> ```
> 
> However, I still get this result below.
> ```
> Simplifying...
> 2020-03-30 08:49:02.853713051 [E:onnxruntime:, sequential_executor.cc:183 Execute] Non-zero status code returned while running Add node. Name:'' Status Message: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:97 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:91 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 2: out of memory ; GPU=0 ; hostname=chieh-Z97X-UD3H ; expr=cudaMalloc((void**)&p, size); 
> Stacktrace:
> 
> Stacktrace:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/__main__.py", line 42, in <module>
>   File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/__main__.py", line 31, in main
>   File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/onnx_simplifier.py", line 303, in simplify
>   File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/onnx_simplifier.py", line 158, in forward_all
>   File "/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/onnx_simplifier.py", line 149, in forward
>   File "/home/chieh/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 142, in run
>     return self._sess.run(output_names, input_feed, run_options)
> onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'' Status Message: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:97 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:91 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 2: out of memory ; GPU=0 ; hostname=chieh-Z97X-UD3H ; expr=cudaMalloc((void**)&p, size); 
> Stacktrace:
> 
> Stacktrace:
> ```
> Do you know how to fix this error?
> 
> Thank you.

Thanks for your report. Could you please send your model to daquexian566@gmail.com? Thanks!

**Comment by chiehpower** [comment]
> Thanks for your report. Could you please send your model to [daquexian566@gmail.com](mailto:daquexian566@gmail.com)? Thanks!

@daquexian 
Thank you! I already sent you my model. 
The thing is that I can run onnx-simplifier by onnxruntime cpu version. Besides it, I confirmed my onnxruntime gpu version which can also work on my pc. 
Hence, I don't think so it is relevant with the model...

**Comment by daquexian** [comment]
> > Thanks for your report. Could you please send your model to [daquexian566@gmail.com](mailto:daquexian566@gmail.com)? Thanks!
> 
> @daquexian
> Thank you! I already sent you my model.
> The thing is that I can run onnx-simplifier by onnxruntime cpu version. Besides it, I confirmed my onnxruntime gpu version which can also work on my pc.
> Hence, I don't think so it is relevant with the model...

Thanks! I also thought that it is likely not relevant to the model. I just use the model to try reproducing the issue. onnxruntime-gpu pypi package needs cuda 10 installed, I'm installing it now and it will take some time :)

**Comment by chiehpower** [comment]
> > > Thanks for your report. Could you please send your model to [daquexian566@gmail.com](mailto:daquexian566@gmail.com)? Thanks!
> > 
> > 
> > @daquexian
> > Thank you! I already sent you my model.
> > The thing is that I can run onnx-simplifier by onnxruntime cpu version. Besides it, I confirmed my onnxruntime gpu version which can also work on my pc.
> > Hence, I don't think so it is relevant with the model...
> 
> Thanks! I also thought that it is likely not relevant to the model. I just use the model to try reproducing the issue. onnxruntime-gpu pypi package needs cuda 10 installed, I'm installing it now and it will take some time :)

No problem! Thanks for your help!

This code is what I tested onnxruntime-gpu that I can use the set_providers to set up the `CPUExecutionProvider` or `CUDAExecutionProvider`. 
```
import onnxruntime as rt
import os
import onnx
import torch

device = torch.device(device='cuda')
pathmodel = os.path.join('model.onnx') # put your frozen onnx model here
model = onnx.load(pathmodel)

onnx.checker.check_model(model)

sess = rt.InferenceSession(pathmodel)
print(sess.get_providers())

print("Set the CPUExecutionProvider ")
sess.set_providers(['CPUExecutionProvider'])
print("Let us check again.")
print(sess.get_providers())

print("Set back to CUDAExecutionProvider ")
sess.set_providers(['CUDAExecutionProvider'])
print("Let us check again.")
print(sess.get_providers())
```
Output: 
```
['CUDAExecutionProvider', 'CPUExecutionProvider']
Set the CPUExecutionProvider 
Let us check again.
['CPUExecutionProvider']
Set back to CUDAExecutionProvider 
Let us check again.
['CUDAExecutionProvider', 'CPUExecutionProvider']
```
So I thought that my onnxruntime-gpu should be no problem...

**Comment by daquexian** [comment]
@chiehpower I have installed onnxruntime-gpu and had a try. It used CPU correctly. Could you verify the code is up to date on your side?

If so, could you please run `python3 -c "import onnxsim; print(onnxsim.__file__)"` to get the installation location of onnxsim, and open the `onnx-simplifier.py` in the same directory, add `print(sess.get_providers())` at line 145?

**Comment by chiehpower** [comment]
Hi @daquexian, 

When I try to show you my information of `print(sess.get_providers())`, I found two important things. 
The first significant point is that `if we modify anything of script, we need to install again.`
```
sudo python3 setup.py install         
```
The second significant thing is that if we have modified the onnxruntime version, we still need to install onnx-simplifier again! And if we install both versions, we cannot only uninstall cpu versions in order to use gpu version. We must uninstall both versions, and then install gpu versions again. Sequentially, should install onnx-simplifier again.

1. Command `python3 -c "import onnxsim; print(onnxsim.__file__)"`
Output:
```
/usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/__init__.py
```
2. Add `print(sess.get_providers())` at line 145.
```
embedmask_case ›› python3 -m onnxsim embedmask_3.onnx embedmask_simplifier_3.onnx                    
Simplifying...
['CPUExecutionProvider']
Checking 0/3...
['CPUExecutionProvider']
['CPUExecutionProvider']
Checking 1/3...
['CPUExecutionProvider']
['CPUExecutionProvider']
Checking 2/3...
['CPUExecutionProvider']
['CPUExecutionProvider']
Ok!
```

Finally it can run without any error!!!
Thank you so much!

Best regars,
Chieh

**Comment by daquexian** [comment]
> Hi @daquexian, 
> 
> When I try to show you my information of `print(sess.get_providers())`, I found two important things. 
> The first significant point is that `if we modify anything of script, we need to install again.`
> ```
> sudo python3 setup.py install         
> ```
> The second significant thing is that if we have modified the onnxruntime version, we still need to install onnx-simplifier again! And if we install both versions, we cannot only uninstall cpu versions in order to use gpu version. We must uninstall both versions, and then install gpu versions again. Sequentially, should install onnx-simplifier again.
> 
> 1. Command `python3 -c "import onnxsim; print(onnxsim.__file__)"`
> Output:
> ```
> /usr/local/lib/python3.6/dist-packages/onnx_simplifier-0.0.0-py3.6.egg/onnxsim/__init__.py
> ```
> 2. Add `print(sess.get_providers())` at line 145.
> ```
> embedmask_case ›› python3 -m onnxsim embedmask_3.onnx embedmask_simplifier_3.onnx                    
> Simplifying...
> ['CPUExecutionProvider']
> Checking 0/3...
> ['CPUExecutionProvider']
> ['CPUExecutionProvider']
> Checking 1/3...
> ['CPUExecutionProvider']
> ['CPUExecutionProvider']
> Checking 2/3...
> ['CPUExecutionProvider']
> ['CPUExecutionProvider']
> Ok!
> ```
> 
> Finally it can run without any error!!!
> Thank you so much!
> 
> Best regars,
> Chieh

Thanks!
